name: Verify

on: pull_request

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Check size
        run: yarn size
